name = "staging-synthetic-cage"
uuid = "cage_537fb3834b07"
app_uuid = "app_1bba8ba15402"
team_uuid = "team_478144181bec"
debug = true
dockerfile = "./Dockerfile"
api_key_auth = true
trx_logging = true
disable_tls_termination = false

[egress]
enabled = true

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
