[package]
name = "data-plane"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
hyper = { version = "0.14.4", features = ["server","http1","http2","tcp","stream","client"] }
tokio = { version = "1.18.0", features = ["net", "macros", "rt", "rt-multi-thread", "io-util", "time"] }
memsec = { version = ">=0.5", default-features = false }
openssl = { version = "0.10.36", features = ["vendored"] }
aws-nitro-enclaves-nsm-api = "0.2.1"
lazy_static = "1.4.0"
async-trait = "0.1.56"
thiserror = "1.0"
bytes = "1"
nom = "7.1.1"
tokio-util = { version = "0.6", features = ["full"] }
futures = "0.3.21"
dns-message-parser = { version = "*", optional = true }
ttl_cache = { version = "*", optional = true }
tokio-rustls = { version = "0.23.4", features = ["dangerous_configuration"] }
tokio-vsock = { version = "0.3.2", optional = true }
tls-parser = "0.11.0"
shared = { path = "../shared", default-features = false }
dashmap = "4.0.2"
serde = { version = "1.0.142", features = ["derive"] }
serde_bytes = "0.11.6"
serde_json = "1.0.83"
sha2 = "0.10.2"
rcgen = { version = "0.9.2", features = ["x509-parser"] }
rand = { version = "0.8.5", optional = true }
clap = { version = "3.1.18", features = ["derive"] }
base64 = "0.13.0"
webpki-roots = "0.22.4"

[dev-dependencies]
tokio-test = "0.4.2"

[features]
default = []
network_egress = ["dep:dns-message-parser","dep:ttl_cache","dep:rand"]
enclave = ["dep:tokio-vsock", "network_egress", "shared/enclave"]
not_enclave = ["network_egress"]
