[package]
name = "control-plane"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["net", "macros", "rt", "rt-multi-thread", "io-util", "time"] }
dashmap = "4.0.2"
trust-dns-resolver = { version = "*" }
dns-message-parser = { version = "~0.6.0" }
bytes = "1"
thiserror = "1.0"
tokio-vsock = { version = "0.3.2", optional = true }
tls-parser = "*"
shared = { path = "../shared" }
rand = { version = "0.8.5" }


[features]
default = []
network_egress = []
enclave = ["dep:tokio-vsock", "network_egress", "shared/enclave"]
not_enclave = ["network_egress"]
