on:
  workflow_run:
    workflows: ["Deploy and Test Cage Staging"]
    types: [completed]

name: Publish Synthetic Alerts/Metrics Staging
jobs:
  publish-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure Staging AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::972197321295:role/synthetics_cloudwatch_put_access
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Publish success metric
        run: aws cloudwatch put-metric-data --metric-name cage-synthetic-status --namespace CagesV2 --unit Count --value 1 --dimensions status=success

  publish-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Notify slack of failure
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "An error occurred while running a Cage synthetic",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "An error occurred while running a Cage synthetic"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Failed action: <${{ github.event.workflow.html_url }} | ${{ github.event.workflow.name }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.workflow_run.html_url }} | View workflow run →>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.repository.html_url }}/tree/${{ github.event.workflow_run.head_sha }}|View repo at head →>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Configure Staging AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::972197321295:role/synthetics_cloudwatch_put_access
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Publish failure metric
        run: aws cloudwatch put-metric-data --metric-name cage-synthetic-status --namespace CagesV2 --unit Count --value 1 --dimensions status=failure